<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "glmorphquiz"
 *
 * Auto generated by Extension Builder 2015-03-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Morphing Quiz',
	'description' => 'In the morphing quiz you get provide the first and the last word of the quiz. You have to find the words in between, but from one word to the next word you are only allowed to change one letter.',
	'category' => 'plugin',
	'author' => 'Gerald Loß',
	'author_email' => 'gerald.loss@gmx.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.3.0',
	'constraints' => array(
		'depends' => 
		array (
		    'php' => '7.3.0-8.0.99',
		    'typo3' => '10.0.0-11.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);